language: python
python:
  - "2.7"
  - "3.3"
  - "3.6"
install:
  - pip install -e .
  - pip install pytest pytest-cov codacy-coverage
script: py.test -v --cov-report xml --cov=j1939 test/
after_script: python-codacy-coverage